name: Release Workflow

permissions:
  contents: write

on:
  push:

env:
  VITE_PLAUSIBLE_API_HOST: ${{ vars.VITE_PLAUSIBLE_API_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Package
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: chathub.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: chathub.zip
